const makeMember = (name, level, moves, label, apiName) => ({
  name,
  label,
  level,
  moves,
  apiName,
});

const makeTrainer = ({
  id,
  name,
  regionId,
  division = 'gym',
  role,
  specialty,
  signature,
  summary,
  team,
  battleStages,
  gameIds,
  gameData,
}) => ({
  id,
  name,
  regionId,
  division,
  role,
  specialty,
  signature,
  summary,
  team,
  battleStages,
  gameIds,
  gameData,
});

const moves = {
  rock: ['Rock Tomb', 'Defense Curl', 'Tackle', 'Rock Throw'],
  water: ['Water Pulse', 'Recover', 'Swift', 'Bubble Beam'],
  electric: ['Shock Wave', 'Thunder Wave', 'Quick Attack', 'Double Team'],
  grass: ['Giga Drain', 'Stun Spore', 'Sleep Powder', 'Acid'],
  poison: ['Toxic', 'Sludge', 'Smokescreen', 'Minimize'],
  psychic: ['Psychic', 'Calm Mind', 'Reflect', 'Recover'],
  fire: ['Fire Blast', 'Fire Spin', 'Take Down', 'Bite'],
  ground: ['Earthquake', 'Rock Blast', 'Sand Tomb', 'Body Slam'],
  ice: ['Ice Beam', 'Surf', 'Hail', 'Safeguard'],
  fighting: ['Brick Break', 'Bulk Up', 'Rock Tomb', 'Counter'],
  ghost: ['Shadow Ball', 'Confuse Ray', 'Hypnosis', 'Dream Eater'],
  dragon: ['Dragon Claw', 'Dragon Dance', 'Hyper Beam', 'Safeguard'],
  dark: ['Dark Pulse', 'Crunch', 'Fake Out', 'Swagger'],
  bug: ['X-Scissor', 'Bug Buzz', 'Protect', 'Double Team'],
  flying: ['Air Slash', 'Aerial Ace', 'Roost', 'Quick Attack'],
  steel: ['Iron Head', 'Metal Claw', 'Flash Cannon', 'Protect'],
  normal: ['Take Down', 'Facade', 'Yawn', 'Rest'],
  fairy: ['Dazzling Gleam', 'Draining Kiss', 'Charm', 'Reflect'],
};

const dianthaPokemonLeagueTeam = [
  makeMember('Hawlucha', 64, ['Swords Dance', 'Flying Press', 'X-Scissor', 'Poison Jab']),
  makeMember('Tyrantrum', 65, ['Head Smash', 'Earthquake', 'Dragon Claw', 'Crunch']),
  makeMember('Aurorus', 65, ['Thunder', 'Blizzard', 'Light Screen', 'Reflect']),
  makeMember('Gourgeist', 65, ['Trick-or-Treat', 'Phantom Force', 'Seed Bomb', 'Shadow Sneak']),
  makeMember('Goodra', 66, ['Dragon Pulse', 'Muddy Water', 'Fire Blast', 'Focus Blast']),
  makeMember('Gardevoir', 68, ['Moonblast', 'Psychic', 'Shadow Ball', 'Thunderbolt']),
];

const makeTeam = (members) =>
  members.map(([name, level, moveType = 'normal', label, apiName]) =>
    makeMember(name, level, moves[moveType] || moves.normal, label, apiName));

const sourceCheckedTrainerTeams = {
  'roark-sinnoh': makeTeam([
    ['Geodude', 12, 'rock'],
    ['Onix', 12, 'rock'],
    ['Cranidos', 14, 'rock'],
  ]),
  'gardenia-sinnoh': makeTeam([
    ['Turtwig', 20, 'grass'],
    ['Cherrim', 20, 'grass'],
    ['Roserade', 22, 'grass'],
  ]),
  'wake-sinnoh': makeTeam([
    ['Gyarados', 33, 'water'],
    ['Quagsire', 34, 'water'],
    ['Floatzel', 37, 'water'],
  ]),
  'maylene-sinnoh': makeTeam([
    ['Meditite', 28, 'fighting'],
    ['Machoke', 29, 'fighting'],
    ['Lucario', 32, 'fighting'],
  ]),
  'fantina-sinnoh': makeTeam([
    ['Duskull', 24, 'ghost'],
    ['Haunter', 24, 'ghost'],
    ['Mismagius', 26, 'ghost'],
  ]),
  'byron-sinnoh': makeTeam([
    ['Magneton', 37, 'electric'],
    ['Steelix', 38, 'steel'],
    ['Bastiodon', 41, 'steel'],
  ]),
  'candice-sinnoh': makeTeam([
    ['Sneasel', 40, 'dark'],
    ['Piloswine', 40, 'ice'],
    ['Abomasnow', 42, 'ice'],
    ['Froslass', 44, 'ice'],
  ]),
  'volkner-sinnoh': makeTeam([
    ['Jolteon', 46, 'electric'],
    ['Raichu', 46, 'electric'],
    ['Luxray', 48, 'electric'],
    ['Electivire', 50, 'electric'],
  ]),
  'aaron-sinnoh': makeTeam([
    ['Yanmega', 49, 'bug'],
    ['Scizor', 49, 'bug'],
    ['Heracross', 51, 'bug'],
    ['Vespiquen', 50, 'bug'],
    ['Drapion', 53, 'poison'],
  ]),
  'bertha-sinnoh': makeTeam([
    ['Whiscash', 50, 'ground'],
    ['Gliscor', 53, 'ground'],
    ['Hippowdon', 52, 'ground'],
    ['Golem', 52, 'rock'],
    ['Rhyperior', 55, 'ground'],
  ]),
  'flint-sinnoh': makeTeam([
    ['Houndoom', 52, 'fire'],
    ['Flareon', 55, 'fire'],
    ['Rapidash', 53, 'fire'],
    ['Infernape', 55, 'fire'],
    ['Magmortar', 57, 'fire'],
  ]),
  'lucian-sinnoh': makeTeam([
    ['Mr. Mime', 53, 'psychic', 'Mr. Mime'],
    ['Espeon', 55, 'psychic'],
    ['Bronzong', 54, 'steel'],
    ['Alakazam', 56, 'psychic'],
    ['Gallade', 59, 'psychic'],
  ]),
  'cynthia-sinnoh': makeTeam([
    ['Spiritomb', 58, 'ghost'],
    ['Togekiss', 60, 'fairy'],
    ['Roserade', 58, 'grass'],
    ['Milotic', 58, 'water'],
    ['Lucario', 60, 'fighting'],
    ['Garchomp', 62, 'dragon'],
  ]),
  'cilan-unova': makeTeam([['Lillipup', 12, 'normal'], ['Pansage', 14, 'grass']]),
  'chili-unova': makeTeam([['Lillipup', 12, 'normal'], ['Pansear', 14, 'fire']]),
  'cress-unova': makeTeam([['Lillipup', 12, 'normal'], ['Panpour', 14, 'water']]),
  'lenora-unova': makeTeam([['Herdier', 18, 'normal'], ['Watchog', 20, 'normal']]),
  'burgh-unova': makeTeam([['Whirlipede', 21, 'bug'], ['Dwebble', 21, 'bug'], ['Leavanny', 23, 'bug']]),
  'elesa-unova': makeTeam([['Emolga', 25, 'electric'], ['Emolga', 25, 'electric'], ['Zebstrika', 27, 'electric']]),
  'clay-unova': makeTeam([['Krokorok', 29, 'ground'], ['Palpitoad', 29, 'water'], ['Excadrill', 31, 'ground']]),
  'skyla-unova': makeTeam([['Swoobat', 33, 'flying'], ['Unfezant', 33, 'flying'], ['Swanna', 35, 'water']]),
  'brycen-unova': makeTeam([['Vanillish', 37, 'ice'], ['Cryogonal', 37, 'ice'], ['Beartic', 39, 'ice']]),
  'drayden-unova': makeTeam([['Fraxure', 41, 'dragon'], ['Druddigon', 41, 'dragon'], ['Haxorus', 43, 'dragon']]),
  'iris-unova': makeTeam([['Fraxure', 41, 'dragon'], ['Druddigon', 41, 'dragon'], ['Haxorus', 43, 'dragon']]),
  'cheren-unova': makeTeam([['Patrat', 11, 'normal'], ['Lillipup', 13, 'normal']]),
  'roxie-unova': makeTeam([['Koffing', 16, 'poison'], ['Whirlipede', 18, 'poison']]),
  'shauntal-unova': makeTeam([['Cofagrigus', 48, 'ghost'], ['Jellicent', 48, 'water'], ['Golurk', 48, 'ground'], ['Chandelure', 50, 'ghost']]),
  'grimsley-unova': makeTeam([['Scrafty', 48, 'dark'], ['Liepard', 48, 'dark'], ['Krookodile', 48, 'ground'], ['Bisharp', 50, 'dark']]),
  'caitlin-unova': makeTeam([['Reuniclus', 48, 'psychic'], ['Musharna', 48, 'psychic'], ['Sigilyph', 48, 'psychic'], ['Gothitelle', 50, 'psychic']]),
  'marshal-unova': makeTeam([['Throh', 48, 'fighting'], ['Sawk', 48, 'fighting'], ['Conkeldurr', 48, 'fighting'], ['Mienshao', 50, 'fighting']]),
  'alder-unova': makeTeam([['Accelgor', 75, 'bug'], ['Bouffalant', 75, 'normal'], ['Druddigon', 75, 'dragon'], ['Escavalier', 75, 'bug'], ['Vanilluxe', 75, 'ice'], ['Volcarona', 77, 'bug']]),
  'viola-kalos': makeTeam([['Surskit', 10, 'water'], ['Vivillon', 12, 'bug']]),
  'grant-kalos': makeTeam([['Amaura', 25, 'rock'], ['Tyrunt', 25, 'rock']]),
  'korrina-kalos': makeTeam([['Mienfoo', 29, 'fighting'], ['Machoke', 28, 'fighting'], ['Hawlucha', 32, 'fighting']]),
  'ramos-kalos': makeTeam([['Jumpluff', 30, 'grass'], ['Weepinbell', 31, 'grass'], ['Gogoat', 34, 'grass']]),
  'clemont-kalos': makeTeam([['Emolga', 35, 'electric'], ['Magneton', 35, 'electric'], ['Heliolisk', 37, 'electric']]),
  'valerie-kalos': makeTeam([['Mawile', 38, 'fairy'], ['Mr. Mime', 39, 'psychic', 'Mr. Mime'], ['Sylveon', 42, 'fairy']]),
  'olympia-kalos': makeTeam([['Sigilyph', 44, 'psychic'], ['Slowking', 45, 'psychic'], ['Meowstic', 48, 'psychic']]),
  'wulfric-kalos': makeTeam([['Abomasnow', 56, 'ice'], ['Cryogonal', 55, 'ice'], ['Avalugg', 59, 'ice']]),
  'malva-kalos': makeTeam([['Pyroar', 63, 'fire'], ['Torkoal', 63, 'fire'], ['Chandelure', 63, 'fire'], ['Talonflame', 65, 'fire']]),
  'siebold-kalos': makeTeam([['Clawitzer', 63, 'water'], ['Gyarados', 63, 'water'], ['Starmie', 63, 'water'], ['Barbaracle', 65, 'water']]),
  'wikstrom-kalos': makeTeam([['Klefki', 63, 'steel'], ['Probopass', 63, 'rock'], ['Scizor', 63, 'bug'], ['Aegislash-shield', 65, 'steel', 'Aegislash']]),
  'drasna-kalos': makeTeam([['Dragalge', 63, 'dragon'], ['Druddigon', 63, 'dragon'], ['Altaria', 63, 'dragon'], ['Noivern', 65, 'dragon']]),
  'diantha-kalos': dianthaPokemonLeagueTeam,
  'milo-galar': makeTeam([['Gossifleur', 19, 'grass'], ['Eldegoss', 20, 'grass']]),
  'nessa-galar': makeTeam([['Goldeen', 22, 'water'], ['Arrokuda', 23, 'water'], ['Drednaw', 24, 'water']]),
  'kabu-galar': makeTeam([['Ninetales', 25, 'fire'], ['Arcanine', 25, 'fire'], ['Centiskorch', 27, 'fire']]),
  'bea-galar': makeTeam([['Hitmontop', 34, 'fighting'], ['Pangoro', 34, 'fighting'], ['Sirfetchd', 35, 'fighting', "Sirfetch'd"], ['Machamp', 36, 'fighting']]),
  'allister-galar': makeTeam([['Yamask-galar', 34, 'ghost', 'Yamask'], ['Mimikyu', 34, 'ghost'], ['Cursola', 35, 'ghost'], ['Gengar', 36, 'ghost']]),
  'opal-galar': makeTeam([['Weezing-galar', 36, 'fairy', 'Weezing'], ['Mawile', 36, 'fairy'], ['Togekiss', 37, 'fairy'], ['Alcremie', 38, 'fairy']]),
  'gordie-galar': makeTeam([['Barbaracle', 40, 'rock'], ['Shuckle', 40, 'rock'], ['Stonjourner', 41, 'rock'], ['Coalossal', 42, 'rock']]),
  'melony-galar': makeTeam([['Frosmoth', 40, 'ice'], ['Darmanitan-galar-standard', 40, 'ice', 'Darmanitan'], ['Eiscue-ice', 41, 'ice', 'Eiscue'], ['Lapras', 42, 'ice']]),
  'piers-galar': makeTeam([['Scrafty', 44, 'dark'], ['Malamar', 45, 'dark'], ['Skuntank', 45, 'poison'], ['Obstagoon', 46, 'dark']]),
  'raihan-galar': makeTeam([['Gigalith', 46, 'rock'], ['Flygon', 47, 'dragon'], ['Sandaconda', 46, 'ground'], ['Duraludon', 48, 'dragon']]),
  'leon-galar': makeTeam([['Aegislash-shield', 62, 'steel', 'Aegislash'], ['Dragapult', 62, 'dragon'], ['Haxorus', 63, 'dragon'], ['Seismitoad', 64, 'water'], ['Cinderace', 64, 'fire'], ['Charizard', 65, 'fire']]),
  'katy-paldea': makeTeam([['Nymble', 14, 'bug'], ['Tarountula', 14, 'bug'], ['Teddiursa', 15, 'normal']]),
  'brassius-paldea': makeTeam([['Petilil', 16, 'grass'], ['Smoliv', 16, 'grass'], ['Sudowoodo', 17, 'rock']]),
  'iono-paldea': makeTeam([['Wattrel', 23, 'electric'], ['Bellibolt', 23, 'electric'], ['Luxio', 23, 'electric'], ['Mismagius', 24, 'ghost']]),
  'kofu-paldea': makeTeam([['Veluza', 29, 'water'], ['Wugtrio', 29, 'water'], ['Crabominable', 30, 'fighting']]),
  'larry-paldea': makeTeam([['Komala', 35, 'normal'], ['Dudunsparce-two-segment', 35, 'normal', 'Dudunsparce'], ['Staraptor', 36, 'flying']]),
  'ryme-paldea': makeTeam([['Banette', 41, 'ghost'], ['Mimikyu', 41, 'ghost'], ['Houndstone', 41, 'ghost'], ['Toxtricity-amped', 42, 'poison', 'Toxtricity']]),
  'tulip-paldea': makeTeam([['Farigiraf', 44, 'psychic'], ['Gardevoir', 44, 'psychic'], ['Espathra', 44, 'psychic'], ['Florges', 45, 'fairy']]),
  'grusha-paldea': makeTeam([['Frosmoth', 47, 'ice'], ['Beartic', 47, 'ice'], ['Cetitan', 47, 'ice'], ['Altaria', 48, 'dragon']]),
  'rika-paldea': makeTeam([['Whiscash', 57, 'ground'], ['Camerupt', 57, 'ground'], ['Donphan', 57, 'ground'], ['Dugtrio', 57, 'ground'], ['Clodsire', 58, 'ground']]),
  'poppy-paldea': makeTeam([['Copperajah', 58, 'steel'], ['Corviknight', 58, 'steel'], ['Bronzong', 58, 'steel'], ['Magnezone', 58, 'electric'], ['Tinkaton', 59, 'steel']]),
  'larry-paldea-elite': makeTeam([['Tropius', 59, 'flying'], ['Oricorio-baile', 59, 'flying', 'Oricorio'], ['Altaria', 59, 'dragon'], ['Staraptor', 59, 'flying'], ['Flamigo', 60, 'flying']]),
  'hassel-paldea': makeTeam([['Noivern', 60, 'dragon'], ['Haxorus', 60, 'dragon'], ['Dragalge', 60, 'dragon'], ['Flapple', 60, 'dragon'], ['Baxcalibur', 61, 'dragon']]),
  'geeta-paldea': makeTeam([['Espathra', 61, 'psychic'], ['Gogoat', 61, 'grass'], ['Veluza', 61, 'water'], ['Avalugg', 61, 'ice'], ['Kingambit', 61, 'dark'], ['Glimmora', 62, 'rock']]),
};

const hoennGameData = {
  roxanne: {
    'ruby-sapphire': { team: makeTeam([['Geodude', 14, 'rock'], ['Nosepass', 15, 'rock']]) },
    emerald: { team: makeTeam([['Geodude', 12, 'rock'], ['Geodude', 12, 'rock'], ['Nosepass', 15, 'rock']]) },
  },
  brawly: {
    'ruby-sapphire': { team: makeTeam([['Machop', 17, 'fighting'], ['Makuhita', 18, 'fighting']]) },
    emerald: { team: makeTeam([['Machop', 16, 'fighting'], ['Meditite', 16, 'psychic'], ['Makuhita', 19, 'fighting']]) },
  },
  wattson: {
    'ruby-sapphire': { team: makeTeam([['Magnemite', 22, 'electric'], ['Voltorb', 20, 'electric'], ['Magneton', 23, 'electric']]) },
    emerald: { team: makeTeam([['Voltorb', 20, 'electric'], ['Magneton', 22, 'electric'], ['Electrike', 20, 'electric'], ['Manectric', 24, 'electric']]) },
  },
  flannery: {
    'ruby-sapphire': { team: makeTeam([['Slugma', 26, 'fire'], ['Slugma', 26, 'fire'], ['Torkoal', 28, 'fire']]) },
    emerald: { team: makeTeam([['Numel', 24, 'fire'], ['Slugma', 24, 'fire'], ['Camerupt', 26, 'fire'], ['Torkoal', 29, 'fire']]) },
  },
  norman: {
    'ruby-sapphire': { team: makeTeam([['Slaking', 28, 'normal'], ['Vigoroth', 30, 'normal'], ['Slaking', 31, 'normal']]) },
    emerald: { team: makeTeam([['Spinda', 27, 'normal'], ['Vigoroth', 27, 'normal'], ['Linoone', 29, 'normal'], ['Slaking', 31, 'normal']]) },
  },
  winona: {
    'ruby-sapphire': { team: makeTeam([['Swellow', 31, 'flying'], ['Pelipper', 30, 'water'], ['Skarmory', 32, 'steel'], ['Altaria', 33, 'dragon']]) },
    emerald: { team: makeTeam([['Swablu', 29, 'flying'], ['Tropius', 29, 'grass'], ['Pelipper', 30, 'water'], ['Skarmory', 31, 'steel'], ['Altaria', 33, 'dragon']]) },
  },
  'liza-tate': {
    'ruby-sapphire': { team: makeTeam([['Lunatone', 42, 'psychic'], ['Solrock', 42, 'psychic']]) },
    emerald: { team: makeTeam([['Claydol', 41, 'psychic'], ['Xatu', 41, 'psychic'], ['Lunatone', 42, 'psychic'], ['Solrock', 42, 'psychic']]) },
  },
  wallace: {
    'ruby-sapphire': { team: makeTeam([['Luvdisc', 40, 'water'], ['Whiscash', 42, 'water'], ['Sealeo', 40, 'ice'], ['Seaking', 42, 'water'], ['Milotic', 43, 'water']]) },
    emerald: {
      division: 'champion',
      role: 'Hoenn Champion',
      specialty: ['water'],
      signature: 'Milotic',
      summary: 'Wallace is the Hoenn Champion in Pokemon Emerald and uses a full Water-type final team.',
      team: makeTeam([['Wailord', 57, 'water'], ['Tentacruel', 55, 'poison'], ['Whiscash', 56, 'water'], ['Ludicolo', 56, 'water'], ['Gyarados', 56, 'water'], ['Milotic', 58, 'water']]),
    },
  },
  juan: {
    emerald: {
      division: 'gym',
      role: 'Sootopolis City Gym Leader',
      specialty: ['water'],
      signature: 'Kingdra',
      summary: 'Juan replaces Wallace as Sootopolis Gym Leader in Pokemon Emerald.',
      team: makeTeam([['Luvdisc', 41, 'water'], ['Whiscash', 41, 'water'], ['Sealeo', 43, 'ice'], ['Crawdaunt', 43, 'water'], ['Kingdra', 46, 'water']]),
    },
  },
  sidney: {
    'ruby-sapphire': { team: makeTeam([['Mightyena', 46, 'dark'], ['Cacturne', 46, 'dark'], ['Shiftry', 48, 'dark'], ['Sharpedo', 48, 'water'], ['Absol', 49, 'dark']]) },
    emerald: { team: makeTeam([['Mightyena', 46, 'dark'], ['Cacturne', 46, 'dark'], ['Shiftry', 48, 'dark'], ['Crawdaunt', 48, 'water'], ['Absol', 49, 'dark']]) },
    'omega-ruby-alpha-sapphire': { battleStages: { rematch: { label: 'Postgame Rematch', team: makeTeam([['Scrafty', 70, 'dark'], ['Shiftry', 70, 'dark'], ['Sharpedo', 70, 'water'], ['Zoroark', 70, 'dark'], ['Mandibuzz', 70, 'dark'], ['Absol', 72, 'dark']]) } } },
  },
  phoebe: {
    'ruby-sapphire': { team: makeTeam([['Dusclops', 48, 'ghost'], ['Banette', 49, 'ghost'], ['Banette', 49, 'ghost'], ['Sableye', 50, 'dark'], ['Dusclops', 51, 'ghost']]) },
    emerald: { team: makeTeam([['Dusclops', 48, 'ghost'], ['Banette', 49, 'ghost'], ['Banette', 49, 'ghost'], ['Sableye', 50, 'dark'], ['Dusclops', 51, 'ghost']]) },
    'omega-ruby-alpha-sapphire': { battleStages: { rematch: { label: 'Postgame Rematch', team: makeTeam([['Banette', 71, 'ghost'], ['Mismagius', 71, 'ghost'], ['Drifblim', 71, 'ghost'], ['Chandelure', 71, 'ghost'], ['Dusknoir', 71, 'ghost'], ['Sableye', 73, 'dark']]) } } },
  },
  glacia: {
    'ruby-sapphire': { team: makeTeam([['Glalie', 50, 'ice'], ['Sealeo', 50, 'ice'], ['Glalie', 52, 'ice'], ['Sealeo', 52, 'ice'], ['Walrein', 53, 'ice']]) },
    emerald: { team: makeTeam([['Glalie', 50, 'ice'], ['Sealeo', 50, 'ice'], ['Glalie', 52, 'ice'], ['Sealeo', 52, 'ice'], ['Walrein', 53, 'ice']]) },
    'omega-ruby-alpha-sapphire': { battleStages: { rematch: { label: 'Postgame Rematch', team: makeTeam([['Abomasnow', 72, 'ice'], ['Beartic', 72, 'ice'], ['Froslass', 72, 'ice'], ['Vanilluxe', 72, 'ice'], ['Walrein', 72, 'ice'], ['Glalie', 74, 'ice']]) } } },
  },
  drake: {
    'ruby-sapphire': { team: makeTeam([['Shelgon', 52, 'dragon'], ['Altaria', 54, 'dragon'], ['Flygon', 53, 'ground'], ['Flygon', 53, 'ground'], ['Salamence', 55, 'dragon']]) },
    emerald: { team: makeTeam([['Shelgon', 52, 'dragon'], ['Altaria', 54, 'dragon'], ['Kingdra', 53, 'water'], ['Flygon', 53, 'ground'], ['Salamence', 55, 'dragon']]) },
    'omega-ruby-alpha-sapphire': { battleStages: { rematch: { label: 'Postgame Rematch', team: makeTeam([['Altaria', 73, 'dragon'], ['Dragalge', 73, 'dragon'], ['Kingdra', 73, 'water'], ['Flygon', 73, 'ground'], ['Haxorus', 73, 'dragon'], ['Salamence', 75, 'dragon']]) } } },
  },
  steven: {
    'ruby-sapphire': { team: makeTeam([['Skarmory', 57, 'steel'], ['Cradily', 56, 'rock'], ['Claydol', 55, 'psychic'], ['Armaldo', 56, 'bug'], ['Aggron', 56, 'steel'], ['Metagross', 58, 'steel']]) },
    emerald: {
      division: 'postgame',
      role: 'Meteor Falls Postgame Boss',
      summary: 'Steven challenges the player in Meteor Falls after the Emerald Champion battle.',
      team: makeTeam([['Skarmory', 77, 'steel'], ['Claydol', 75, 'psychic'], ['Aggron', 76, 'steel'], ['Cradily', 76, 'rock'], ['Armaldo', 76, 'bug'], ['Metagross', 78, 'steel']]),
    },
    'omega-ruby-alpha-sapphire': { battleStages: { rematch: { label: 'Postgame Rematch', team: makeTeam([['Skarmory', 77, 'steel'], ['Claydol', 77, 'psychic'], ['Carbink', 77, 'rock'], ['Aerodactyl', 77, 'rock'], ['Aggron', 77, 'steel'], ['Metagross', 79, 'steel']]) } } },
  },
};

const getHoennGameData = (name) => hoennGameData[name.toLowerCase().replace(/[^a-z0-9]+/g, '-')] || {};

const unovaGameData = {
  shauntal: {
    'black-white': { battleStages: { rematch: { label: 'Postgame Rematch', team: makeTeam([['Cofagrigus', 71, 'ghost'], ['Jellicent', 71, 'water'], ['Froslass', 71, 'ice'], ['Drifblim', 71, 'ghost'], ['Golurk', 71, 'ground'], ['Chandelure', 73, 'ghost']]) } } },
  },
  grimsley: {
    'black-white': { battleStages: { rematch: { label: 'Postgame Rematch', team: makeTeam([['Sharpedo', 71, 'water'], ['Liepard', 71, 'dark'], ['Scrafty', 71, 'dark'], ['Drapion', 71, 'poison'], ['Krookodile', 71, 'ground'], ['Bisharp', 73, 'dark']]) } } },
  },
  caitlin: {
    'black-white': { battleStages: { rematch: { label: 'Postgame Rematch', team: makeTeam([['Musharna', 71, 'psychic'], ['Sigilyph', 71, 'psychic'], ['Bronzong', 71, 'steel'], ['Reuniclus', 71, 'psychic'], ['Gothitelle', 71, 'psychic'], ['Metagross', 73, 'steel']]) } } },
  },
  marshal: {
    'black-white': { battleStages: { rematch: { label: 'Postgame Rematch', team: makeTeam([['Breloom', 71, 'fighting'], ['Throh', 71, 'fighting'], ['Sawk', 71, 'fighting'], ['Toxicroak', 71, 'poison'], ['Mienshao', 71, 'fighting'], ['Conkeldurr', 73, 'fighting']]) } } },
  },
};

const getUnovaGameData = (name) => unovaGameData[name.toLowerCase().replace(/[^a-z0-9]+/g, '-')] || {};

const legendsZaTrainers = [
  makeTrainer({
    id: 'urbain-legends-za',
    name: 'Urbain',
    regionId: 'legends-za',
    division: 'rival',
    role: 'Team MZ Leader and Rival',
    specialty: ['mixed'],
    signature: 'Manectric',
    summary: 'Urbain leads Team MZ from Hotel Z and uses the two first partners not chosen by the player alongside Mega Manectric.',
    gameIds: ['legends-za'],
    team: makeTeam([['Croconaw', 25, 'water'], ['Pignite', 25, 'fire'], ['Manectric', 26, 'electric', 'Mega Manectric', 'manectric-mega']]),
  }),
  makeTrainer({
    id: 'lida-legends-za',
    name: 'Lida',
    regionId: 'legends-za',
    division: 'special',
    role: 'Team MZ Member',
    specialty: ['water'],
    signature: 'Staryu',
    summary: 'Lida is a dancer and Team MZ member whose partner Staryu later evolves and gains the power to Mega Evolve.',
    gameIds: ['legends-za'],
    team: makeTeam([['Clauncher', 22, 'water'], ['Vanillite', 22, 'ice'], ['Staryu', 23, 'water']]),
  }),
  makeTrainer({
    id: 'naveen-legends-za',
    name: 'Naveen',
    regionId: 'legends-za',
    division: 'special',
    role: 'Team MZ Member and Fashion Designer',
    specialty: ['dark', 'bug'],
    signature: 'Scraggy',
    summary: 'Naveen is Team MZ\'s aspiring fashion designer and battles with a team led by his partner Scraggy.',
    gameIds: ['legends-za'],
    team: makeTeam([['Spinarak', 16, 'bug'], ['Sableye', 16, 'dark'], ['Scraggy', 17, 'fighting']]),
  }),
  makeTrainer({
    id: 'vinnie-legends-za',
    name: 'Vinnie',
    regionId: 'legends-za',
    division: 'royale',
    role: 'Quasartico Secretary and Z-A Royale Opponent',
    specialty: ['mixed'],
    signature: 'Drampa',
    summary: 'Vinnie is Jett\'s efficient secretary and the special promotion opponent whose ace is Mega Drampa.',
    gameIds: ['legends-za'],
    team: makeTeam([['Houndoom', 30, 'dark'], ['Sharpedo', 30, 'water'], ['Buneary', 30, 'normal'], ['Drampa', 32, 'dragon', 'Mega Drampa', 'drampa-mega']]),
  }),
  makeTrainer({
    id: 'canari-legends-za',
    name: 'Canari',
    regionId: 'legends-za',
    division: 'royale',
    role: 'DYN4MO Streamer and Rank F Opponent',
    specialty: ['electric'],
    signature: 'Eelektross',
    summary: 'Canari is Lumiose City\'s popular gamer and streamer, using an Electric team crowned by Mega Eelektross.',
    gameIds: ['legends-za'],
    team: makeTeam([['Heliolisk', 37, 'electric'], ['Ampharos', 38, 'electric'], ['Stunfisk', 38, 'electric'], ['Eelektross', 39, 'electric', 'Mega Eelektross', 'eelektross-mega']]),
  }),
  makeTrainer({
    id: 'ivor-legends-za',
    name: 'Ivor',
    regionId: 'legends-za',
    division: 'royale',
    role: 'Fist of Justice Leader and Rank E Opponent',
    specialty: ['fighting'],
    signature: 'Falinks',
    summary: 'Ivor leads the Fist of Justice and tests the player with a physical Fighting team and Mega Falinks.',
    gameIds: ['legends-za'],
    team: makeTeam([['Heracross', 45, 'fighting'], ['Medicham', 46, 'fighting'], ['Machamp', 46, 'fighting'], ['Falinks', 47, 'fighting', 'Mega Falinks', 'falinks-mega']]),
  }),
  makeTrainer({
    id: 'gwynn-legends-za',
    name: 'Gwynn',
    regionId: 'legends-za',
    division: 'special',
    role: 'Fist of Justice Assistant',
    specialty: ['ghost'],
    signature: 'Chandelure',
    summary: 'Gwynn is Ivor\'s assistant and a Ghost-type specialist whose partner is Mega Chandelure.',
    gameIds: ['legends-za'],
    team: makeTeam([['Banette', 43, 'ghost'], ['Gourgeist-small', 44, 'ghost', 'Gourgeist'], ['Chandelure', 45, 'ghost', 'Mega Chandelure', 'chandelure-mega']]),
  }),
  makeTrainer({
    id: 'corbeau-legends-za',
    name: 'Corbeau',
    regionId: 'legends-za',
    division: 'royale',
    role: 'Rust Syndicate Boss and Rank D Opponent',
    specialty: ['poison'],
    signature: 'Scolipede',
    summary: 'Corbeau leads the Rust Syndicate and uses a Poison-centered promotion team with Mega Scolipede.',
    gameIds: ['legends-za'],
    team: makeTeam([['Arbok', 50, 'poison'], ['Gyarados', 51, 'water'], ['Roserade', 51, 'poison'], ['Scolipede', 52, 'poison', 'Mega Scolipede', 'scolipede-mega']]),
  }),
  makeTrainer({
    id: 'philippe-legends-za',
    name: 'Philippe',
    regionId: 'legends-za',
    division: 'special',
    role: 'Rust Syndicate Administrator',
    specialty: ['steel'],
    signature: 'Skarmory',
    summary: 'Philippe is Corbeau\'s trusted administrator and fights with a durable Steel team led by Mega Skarmory.',
    gameIds: ['legends-za'],
    team: makeTeam([['Steelix', 46, 'steel'], ['Scizor', 46, 'bug'], ['Skarmory', 47, 'steel', 'Mega Skarmory', 'skarmory-mega']]),
  }),
  makeTrainer({
    id: 'lebanne-legends-za',
    name: 'Lebanne',
    regionId: 'legends-za',
    division: 'special',
    role: 'Society of Battle Connoisseurs Right Hand',
    specialty: ['dragon'],
    signature: 'Dragalge',
    summary: 'Lebanne is Jacinthe\'s fierce right hand and uses an aggressive Dragon team led by Mega Dragalge.',
    gameIds: ['legends-za'],
    team: makeTeam([['Noivern', 53, 'dragon'], ['Tyrantrum', 53, 'dragon'], ['Garchomp', 53, 'dragon'], ['Dragalge', 54, 'dragon', 'Mega Dragalge', 'dragalge-mega']]),
  }),
  makeTrainer({
    id: 'jacinthe-legends-za',
    name: 'Jacinthe',
    regionId: 'legends-za',
    division: 'royale',
    role: 'SBC Leader and Rank C Opponent',
    specialty: ['fairy'],
    signature: 'Clefable',
    summary: 'Jacinthe leads the Society of Battle Connoisseurs and fields an elegant Fairy team with Mega Clefable.',
    gameIds: ['legends-za'],
    team: makeTeam([['Carbink', 57, 'fairy'], ['Mawile', 58, 'fairy'], ['Gardevoir', 58, 'fairy'], ['Aurorus', 58, 'ice'], ['Clefable', 59, 'fairy', 'Mega Clefable', 'clefable-mega']]),
  }),
  makeTrainer({
    id: 'tarragon-legends-za',
    name: 'Tarragon',
    regionId: 'legends-za',
    division: 'special',
    role: 'Racine Construction President',
    specialty: ['ground'],
    signature: 'Excadrill',
    summary: 'Tarragon runs Racine Construction, promotes his granddaughter Canari, and battles with Mega Excadrill.',
    gameIds: ['legends-za'],
    team: makeTeam([['Hippowdon', 36, 'ground'], ['Diggersby', 36, 'ground'], ['Excadrill', 37, 'ground', 'Mega Excadrill', 'excadrill-mega']]),
  }),
  makeTrainer({
    id: 'emma-legends-za',
    name: 'Emma',
    regionId: 'legends-za',
    division: 'special',
    role: 'Lumiose Detective',
    specialty: ['mixed'],
    signature: 'Malamar',
    summary: 'Emma returns as Lumiose City\'s lead detective with a varied team of Mega-capable partners headed by Mega Malamar.',
    gameIds: ['legends-za'],
    team: makeTeam([['Ampharos', 57, 'electric'], ['Mawile', 57, 'steel'], ['Lucario', 57, 'fighting'], ['Lopunny', 57, 'normal'], ['Malamar', 58, 'dark', 'Mega Malamar', 'malamar-mega']]),
  }),
  makeTrainer({
    id: 'griselle-legends-za',
    name: 'Griselle',
    regionId: 'legends-za',
    division: 'royale',
    role: 'Team Flare Nouveau Administrator',
    specialty: ['fire'],
    signature: 'Pyroar',
    summary: 'Griselle is a former Team Flare member whose diverse firepower culminates in Mega Pyroar.',
    gameIds: ['legends-za'],
    team: makeTeam([['Talonflame', 59, 'fire'], ['Camerupt', 59, 'fire'], ['Aerodactyl', 60, 'rock'], ['Metagross', 60, 'steel'], ['Pyroar', 61, 'fire', 'Mega Pyroar', 'pyroar-mega']]),
  }),
  makeTrainer({
    id: 'grisham-legends-za',
    name: 'Grisham',
    regionId: 'legends-za',
    division: 'royale',
    role: 'Team Flare Nouveau Leader and Rank B Opponent',
    specialty: ['dark', 'fire'],
    signature: 'Charizard',
    summary: 'Grisham leads Team Flare Nouveau and stands between the player and Rank A with Mega Charizard X.',
    gameIds: ['legends-za'],
    team: makeTeam([['Pangoro', 61, 'dark'], ['Malamar', 61, 'dark'], ['Pyroar', 61, 'fire', undefined, 'pyroar-male'], ['Tyranitar', 62, 'dark'], ['Salamence', 62, 'dragon'], ['Charizard', 63, 'fire', 'Mega Charizard X', 'charizard-mega-x']]),
  }),
  makeTrainer({
    id: 'korrina-legends-za',
    name: 'Korrina',
    regionId: 'legends-za',
    division: 'special',
    role: 'Mega Evolution Successor and Team MZ Member',
    specialty: ['fighting', 'steel'],
    signature: 'Lucario',
    summary: 'Korrina returns in Mega Dimension as Team MZ\'s Mega Evolution expert and challenges the player with Mega Lucario Z.',
    gameIds: ['legends-za'],
    team: [makeMember('Lucario', 100, ['Extreme Speed', 'Hyper Beam', 'Focus Blast', 'Detect'], 'Mega Lucario Z', 'lucario-mega-z')],
  }),
];

export const TRAINERDEX_OPTIONS = [
  { id: 'kanto', label: 'FireRed / LeafGreen', region: 'Kanto', art: ['FireRed.png', 'LeafGreen.png'], games: [{ id: 'firered-leafgreen', label: 'FireRed LeafGreen' }, { id: 'heartgold-soulsilver', label: 'HeartGold SoulSilver' }] },
  { id: 'johto', label: 'HeartGold / SoulSilver', region: 'Johto', art: ['HeartGold.jpg', 'SoulSilver.jpg'], games: [{ id: 'heartgold-soulsilver', label: 'HeartGold SoulSilver' }, { id: 'gold-silver', label: 'Gold Silver' }] },
  { id: 'hoenn', label: 'Omega Ruby / Alpha Sapphire', region: 'Hoenn', art: ['OmegaRuby.png', 'AlphaSapphire.png'], games: [{ id: 'omega-ruby-alpha-sapphire', label: 'Omega Ruby Alpha Sapphire' }, { id: 'emerald', label: 'Emerald' }, { id: 'ruby-sapphire', label: 'Ruby Sapphire' }] },
  { id: 'sinnoh', label: 'Diamond / Pearl / Platinum', region: 'Sinnoh', art: ['Diamond.jpg', 'Pearl.jpg', 'Platinum.png'], games: [{ id: 'platinum', label: 'Platinum' }, { id: 'diamond-pearl', label: 'Diamond Pearl' }] },
  { id: 'unova', label: 'Black / White / Black 2 / White 2', region: 'Unova', art: ['Black.png', 'White.png'], games: [{ id: 'black-white', label: 'Black White' }, { id: 'black-2-white-2', label: 'Black 2 White 2' }] },
  { id: 'kalos', label: 'X / Y', region: 'Kalos', art: ['X.png', 'Y.png'], games: [{ id: 'x-y', label: 'X Y' }] },
  { id: 'alola', label: 'Sun / Moon', region: 'Alola', art: ['Sun.png', 'Moon.png'], games: [{ id: 'sun-moon', label: 'Sun Moon' }, { id: 'ultra-sun-ultra-moon', label: 'Ultra Sun Ultra Moon' }] },
  { id: 'galar', label: 'Sword / Shield', region: 'Galar', art: ['Sword.png', 'Shield.png'], games: [{ id: 'sword-shield', label: 'Sword Shield' }] },
  { id: 'paldea', label: 'Scarlet / Violet', region: 'Paldea', art: ['Scarlet.png', 'Violet.png'], games: [{ id: 'scarlet-violet', label: 'Scarlet Violet' }] },
  { id: 'legends-za', label: 'Legends: Z-A', region: 'Lumiose City', art: ['Z-A.jpg'], games: [{ id: 'legends-za', label: 'Legends: Z-A' }] },
];

export const TRAINER_GROUPS = [
  { id: 'royale', label: 'Z-A Royale' },
  { id: 'gym', label: 'Gym Leaders' },
  { id: 'kahuna', label: 'Kahunas' },
  { id: 'elite', label: 'Elite Four' },
  { id: 'champion', label: 'Champions' },
  { id: 'rival', label: 'Rivals' },
  { id: 'postgame', label: 'Postgame Bosses' },
  { id: 'facility', label: 'Facility Bosses' },
  { id: 'special', label: 'Special Trainers' },
];

export const TRAINERDEX_TRAINERS = [
  makeTrainer({
    id: 'brock-kanto',
    name: 'Brock',
    regionId: 'kanto',
    role: 'Pewter City Gym Leader',
    specialty: ['rock'],
    signature: 'Onix',
    summary: 'Brock awards the Boulder Badge and tests early teams with Rock-type defense.',
    team: [makeMember('Geodude', 12, ['Tackle', 'Defense Curl', 'Rock Tomb']), makeMember('Onix', 14, ['Tackle', 'Bind', 'Rock Tomb'])],
    gameData: {
      'heartgold-soulsilver': {
        team: makeTeam([['Graveler', 51, 'rock'], ['Rhyhorn', 51, 'ground'], ['Omastar', 53, 'rock'], ['Kabutops', 52, 'rock'], ['Onix', 54, 'rock']]),
        battleStages: {
          rematch: {
            label: 'Fighting Dojo Rematch',
            team: makeTeam([['Golem', 55, 'rock'], ['Relicanth', 54, 'water'], ['Omastar', 56, 'rock'], ['Kabutops', 55, 'rock'], ['Onix', 61, 'rock'], ['Rampardos', 57, 'rock']]),
          },
        },
      },
    },
  }),
  makeTrainer({
    id: 'misty-kanto',
    name: 'Misty',
    regionId: 'kanto',
    role: 'Cerulean City Gym Leader',
    specialty: ['water'],
    signature: 'Staryu',
    summary: 'Misty awards the Cascade Badge and pressures Kanto teams with fast Water Pokemon.',
    team: [makeMember('Staryu', 18, ['Tackle', 'Harden', 'Recover', 'Water Pulse']), makeMember('Starmie', 21, ['Rapid Spin', 'Swift', 'Recover', 'Water Pulse'])],
    gameData: {
      'heartgold-soulsilver': {
        team: makeTeam([['Golduck', 49, 'water'], ['Quagsire', 49, 'water'], ['Lapras', 52, 'water'], ['Starmie', 54, 'water']]),
        battleStages: {
          rematch: {
            label: 'Fighting Dojo Rematch',
            team: makeTeam([['Starmie', 60, 'water'], ['Quagsire', 56, 'water'], ['Lapras', 56, 'water'], ['Lanturn', 54, 'water'], ['Floatzel', 54, 'water'], ['Milotic', 60, 'water']]),
          },
        },
      },
    },
  }),
  makeTrainer({
    id: 'lt-surge-kanto',
    name: 'Lt. Surge',
    regionId: 'kanto',
    role: 'Vermilion City Gym Leader',
    specialty: ['electric'],
    signature: 'Raichu',
    summary: 'Lt. Surge awards the Thunder Badge and leans on paralysis and quick Electric attacks.',
    team: [makeMember('Voltorb', 21, moves.electric), makeMember('Pikachu', 18, moves.electric), makeMember('Raichu', 24, moves.electric)],
    gameData: {
      'heartgold-soulsilver': {
        team: makeTeam([['Raichu', 51, 'electric'], ['Electrode', 47, 'electric'], ['Electrode', 47, 'electric'], ['Magneton', 47, 'electric'], ['Electabuzz', 53, 'electric']]),
        battleStages: {
          rematch: {
            label: 'Fighting Dojo Rematch',
            team: makeTeam([['Raichu', 60, 'electric'], ['Manectric', 52, 'electric'], ['Magnezone', 52, 'electric'], ['Electrode', 52, 'electric'], ['Pachirisu', 58, 'electric'], ['Electivire', 56, 'electric']]),
          },
        },
      },
    },
  }),
  makeTrainer({
    id: 'erika-kanto',
    name: 'Erika',
    regionId: 'kanto',
    role: 'Celadon City Gym Leader',
    specialty: ['grass', 'poison'],
    signature: 'Vileplume',
    summary: 'Erika awards the Rainbow Badge with a status-heavy Grass team.',
    team: [makeMember('Victreebel', 29, moves.grass), makeMember('Tangela', 24, ['Constrict', 'Ingrain', 'Giga Drain']), makeMember('Vileplume', 29, moves.grass)],
    gameIds: ['firered-leafgreen'],
  }),
  makeTrainer({
    id: 'koga-kanto',
    name: 'Koga',
    regionId: 'kanto',
    role: 'Fuchsia City Gym Leader',
    specialty: ['poison'],
    signature: 'Weezing',
    summary: 'Koga awards the Soul Badge and uses poison, evasion, and disruptive tactics.',
    team: [makeMember('Koffing', 37, moves.poison), makeMember('Koffing', 37, moves.poison), makeMember('Muk', 39, moves.poison), makeMember('Weezing', 43, moves.poison)],
    gameIds: ['firered-leafgreen'],
  }),
  makeTrainer({
    id: 'sabrina-kanto',
    name: 'Sabrina',
    regionId: 'kanto',
    role: 'Saffron City Gym Leader',
    specialty: ['psychic'],
    signature: 'Alakazam',
    summary: 'Sabrina awards the Marsh Badge and uses high-special Psychic Pokemon.',
    team: [makeMember('Kadabra', 38, moves.psychic), makeMember('Mr. Mime', 37, ['Barrier', 'Psybeam', 'Baton Pass', 'Calm Mind']), makeMember('Venomoth', 38, ['Gust', 'Psybeam', 'Supersonic', 'Leech Life']), makeMember('Alakazam', 43, moves.psychic)],
    gameIds: ['firered-leafgreen'],
  }),
  makeTrainer({
    id: 'blaine-kanto',
    name: 'Blaine',
    regionId: 'kanto',
    role: 'Cinnabar Island Gym Leader',
    specialty: ['fire'],
    signature: 'Arcanine',
    summary: 'Blaine awards the Volcano Badge after a quiz-themed Fire-type Gym.',
    team: [makeMember('Growlithe', 42, moves.fire), makeMember('Ponyta', 40, ['Stomp', 'Bounce', 'Fire Spin', 'Fire Blast']), makeMember('Rapidash', 42, ['Stomp', 'Bounce', 'Fire Spin', 'Fire Blast']), makeMember('Arcanine', 47, moves.fire)],
    gameIds: ['firered-leafgreen'],
  }),
  makeTrainer({
    id: 'giovanni-kanto',
    name: 'Giovanni',
    regionId: 'kanto',
    role: 'Viridian City Gym Leader',
    specialty: ['ground'],
    signature: 'Rhydon',
    summary: 'Giovanni is Team Rocket\'s boss and Kanto\'s final Gym Leader.',
    team: [makeMember('Rhyhorn', 45, moves.ground), makeMember('Dugtrio', 42, moves.ground), makeMember('Nidoqueen', 44, moves.ground), makeMember('Nidoking', 45, moves.ground), makeMember('Rhydon', 50, moves.ground)],
    gameIds: ['firered-leafgreen'],
  }),
  makeTrainer({
    id: 'lorelei-kanto',
    name: 'Lorelei',
    regionId: 'kanto',
    division: 'elite',
    role: 'Kanto Elite Four',
    specialty: ['ice', 'water'],
    signature: 'Lapras',
    summary: 'Lorelei opens the Kanto Elite Four with Ice and Water Pokemon.',
    team: [makeMember('Dewgong', 52, moves.ice), makeMember('Cloyster', 51, moves.ice), makeMember('Slowbro', 52, ['Surf', 'Ice Beam', 'Amnesia', 'Yawn']), makeMember('Jynx', 54, ['Lovely Kiss', 'Ice Punch', 'Attract', 'Double Slap']), makeMember('Lapras', 54, ['Surf', 'Body Slam', 'Confuse Ray', 'Ice Beam'])],
    gameIds: ['firered-leafgreen'],
  }),
  makeTrainer({
    id: 'bruno-kanto',
    name: 'Bruno',
    regionId: 'kanto',
    division: 'elite',
    role: 'Kanto / Johto Elite Four',
    specialty: ['fighting', 'rock'],
    signature: 'Machamp',
    summary: 'Bruno mixes Fighting specialists with Rock-type support.',
    team: [makeMember('Onix', 51, moves.rock), makeMember('Hitmonchan', 53, moves.fighting), makeMember('Hitmonlee', 53, moves.fighting), makeMember('Onix', 54, moves.rock), makeMember('Machamp', 56, moves.fighting)],
    gameIds: ['firered-leafgreen'],
  }),
  makeTrainer({
    id: 'agatha-kanto',
    name: 'Agatha',
    regionId: 'kanto',
    division: 'elite',
    role: 'Kanto Elite Four',
    specialty: ['ghost', 'poison'],
    signature: 'Gengar',
    summary: 'Agatha uses Ghost and Poison tactics built around status and confusion.',
    team: [makeMember('Gengar', 54, moves.ghost), makeMember('Golbat', 54, ['Confuse Ray', 'Air Cutter', 'Bite', 'Poison Fang']), makeMember('Haunter', 53, moves.ghost), makeMember('Arbok', 56, moves.poison), makeMember('Gengar', 58, moves.ghost)],
    gameIds: ['firered-leafgreen'],
  }),
  makeTrainer({
    id: 'lance-kanto',
    name: 'Lance',
    regionId: 'kanto',
    division: 'elite',
    role: 'Kanto Elite Four',
    specialty: ['dragon', 'flying'],
    signature: 'Dragonite',
    summary: 'Lance closes the Kanto Elite Four with Dragon-themed Pokemon.',
    team: [makeMember('Gyarados', 56, ['Dragon Rage', 'Twister', 'Bite', 'Hyper Beam']), makeMember('Dragonair', 54, moves.dragon), makeMember('Dragonair', 54, moves.dragon), makeMember('Aerodactyl', 58, ['Ancient Power', 'Wing Attack', 'Scary Face', 'Hyper Beam']), makeMember('Dragonite', 60, moves.dragon)],
    gameIds: ['firered-leafgreen'],
  }),
  makeTrainer({
    id: 'blue-kanto',
    name: 'Blue',
    regionId: 'kanto',
    division: 'champion',
    role: 'Kanto Champion',
    specialty: ['mixed'],
    signature: 'Charizard',
    summary: 'Blue is the Kanto Champion and the final FireRed / LeafGreen League battle.',
    team: [makeMember('Pidgeot', 59, moves.flying), makeMember('Alakazam', 57, moves.psychic), makeMember('Rhydon', 59, moves.ground), makeMember('Exeggutor', 59, moves.grass), makeMember('Gyarados', 61, moves.water), makeMember('Charizard', 63, moves.fire)],
    gameData: {
      'firered-leafgreen': {
        battleStages: {
          rematch: {
            label: 'Sevii Islands Rematch',
            team: [makeMember('Pidgeot', 72, moves.flying), makeMember('Alakazam', 73, moves.psychic), makeMember('Rhydon', 72, moves.ground), makeMember('Exeggutor', 73, moves.grass), makeMember('Gyarados', 73, moves.water), makeMember('Charizard', 75, moves.fire)],
          },
        },
      },
      'heartgold-soulsilver': {
        division: 'gym',
        role: 'Viridian City Gym Leader',
        signature: 'Pidgeot',
        summary: 'Blue returns as Viridian City Gym Leader in HeartGold / SoulSilver and can be rematched at the Fighting Dojo.',
        team: [makeMember('Exeggutor', 55, moves.grass), makeMember('Arcanine', 58, moves.fire), makeMember('Rhydon', 58, moves.ground), makeMember('Gyarados', 52, moves.water), makeMember('Machamp', 56, moves.fighting), makeMember('Pidgeot', 60, moves.flying)],
        battleStages: {
          rematch: {
            label: 'Fighting Dojo Rematch',
            team: [makeMember('Exeggutor', 67, moves.grass), makeMember('Machamp', 69, moves.fighting), makeMember('Rhyperior', 70, moves.ground), makeMember('Arcanine', 68, moves.fire), makeMember('Tyranitar', 70, moves.dark), makeMember('Pidgeot', 72, moves.flying)],
          },
        },
      },
    },
  }),
  ...[
    ['Falkner', 'Violet City Gym Leader', ['flying'], 'Pidgeotto', [makeMember('Pidgey', 9, moves.flying), makeMember('Pidgeotto', 13, moves.flying)]],
    ['Bugsy', 'Azalea Town Gym Leader', ['bug'], 'Scyther', [makeMember('Metapod', 15, moves.bug), makeMember('Kakuna', 15, moves.bug), makeMember('Scyther', 17, moves.bug)]],
    ['Whitney', 'Goldenrod City Gym Leader', ['normal'], 'Miltank', [makeMember('Clefairy', 17, moves.fairy), makeMember('Miltank', 19, moves.normal)]],
    ['Morty', 'Ecruteak City Gym Leader', ['ghost'], 'Gengar', [makeMember('Gastly', 21, moves.ghost), makeMember('Haunter', 21, moves.ghost), makeMember('Haunter', 23, moves.ghost), makeMember('Gengar', 25, moves.ghost)]],
    ['Chuck', 'Cianwood City Gym Leader', ['fighting'], 'Poliwrath', [makeMember('Primeape', 29, moves.fighting), makeMember('Poliwrath', 31, moves.water)]],
    ['Jasmine', 'Olivine City Gym Leader', ['steel'], 'Steelix', [makeMember('Magnemite', 30, moves.electric), makeMember('Magnemite', 30, moves.electric), makeMember('Steelix', 35, moves.steel)]],
    ['Pryce', 'Mahogany Town Gym Leader', ['ice'], 'Piloswine', [makeMember('Seel', 30, moves.ice), makeMember('Dewgong', 32, moves.ice), makeMember('Piloswine', 34, moves.ground)]],
    ['Clair', 'Blackthorn City Gym Leader', ['dragon'], 'Kingdra', [makeMember('Dragonair', 38, moves.dragon), makeMember('Dragonair', 38, moves.dragon), makeMember('Dragonair', 38, moves.dragon), makeMember('Kingdra', 41, moves.water)]],
  ].map(([name, role, specialty, signature, team]) => makeTrainer({
    id: `${name.toLowerCase()}-johto`,
    name,
    regionId: 'johto',
    role,
    specialty,
    signature,
    summary: `${name} is a Johto Gym Leader whose badge battle focuses on ${specialty.join(' / ')} Pokemon.`,
    team,
  })),
  makeTrainer({
    id: 'will-johto',
    name: 'Will',
    regionId: 'johto',
    division: 'elite',
    role: 'Johto Elite Four',
    specialty: ['psychic'],
    signature: 'Xatu',
    summary: 'Will opens Johto\'s Elite Four with a Psychic-focused team built around Xatu.',
    team: [makeMember('Xatu', 40, moves.psychic), makeMember('Jynx', 41, moves.ice), makeMember('Exeggutor', 41, moves.grass), makeMember('Slowbro', 41, moves.water), makeMember('Xatu', 42, moves.psychic)],
  }),
  makeTrainer({
    id: 'koga-johto',
    name: 'Koga',
    regionId: 'johto',
    division: 'elite',
    role: 'Johto Elite Four',
    specialty: ['poison'],
    signature: 'Crobat',
    summary: 'Koga joins the Johto Elite Four after leaving the Fuchsia Gym.',
    team: [makeMember('Ariados', 40, moves.poison), makeMember('Venomoth', 41, ['Supersonic', 'Gust', 'Psychic', 'Toxic']), makeMember('Muk', 42, moves.poison), makeMember('Forretress', 43, moves.steel), makeMember('Crobat', 44, ['Wing Attack', 'Confuse Ray', 'Toxic', 'Double Team'])],
  }),
  makeTrainer({
    id: 'bruno-johto',
    name: 'Bruno',
    regionId: 'johto',
    division: 'elite',
    role: 'Johto Elite Four',
    specialty: ['fighting'],
    signature: 'Machamp',
    summary: 'Bruno returns in Johto with a mostly Fighting-type team.',
    team: [makeMember('Hitmontop', 42, moves.fighting), makeMember('Hitmonlee', 42, moves.fighting), makeMember('Hitmonchan', 42, moves.fighting), makeMember('Onix', 43, moves.rock), makeMember('Machamp', 46, moves.fighting)],
  }),
  makeTrainer({
    id: 'karen-johto',
    name: 'Karen',
    regionId: 'johto',
    division: 'elite',
    role: 'Johto Elite Four',
    specialty: ['dark'],
    signature: 'Houndoom',
    summary: 'Karen is Johto\'s Dark-type Elite Four member and closes the Elite Four before the Champion battle.',
    team: [makeMember('Umbreon', 42, moves.dark), makeMember('Vileplume', 42, moves.grass), makeMember('Murkrow', 44, moves.flying), makeMember('Gengar', 45, moves.ghost), makeMember('Houndoom', 47, moves.dark)],
  }),
  makeTrainer({
    id: 'lance-johto',
    name: 'Lance',
    regionId: 'johto',
    division: 'champion',
    role: 'Johto Champion',
    specialty: ['dragon', 'flying'],
    signature: 'Dragonite',
    summary: 'Lance serves as Champion for the Johto League.',
    team: [makeMember('Gyarados', 46, ['Flail', 'Waterfall', 'Bite', 'Dragon Pulse']), makeMember('Dragonite', 49, moves.dragon), makeMember('Dragonite', 49, moves.dragon), makeMember('Aerodactyl', 48, ['Rock Slide', 'Aerial Ace', 'Crunch', 'Thunder Fang']), makeMember('Charizard', 48, moves.fire), makeMember('Dragonite', 50, moves.dragon)],
  }),
  makeTrainer({
    id: 'red-johto',
    name: 'Red',
    regionId: 'johto',
    division: 'special',
    role: 'Mt. Silver Trainer',
    specialty: ['mixed'],
    signature: 'Pikachu',
    summary: 'Red is the silent final postgame trainer waiting at the summit of Mt. Silver.',
    team: [
      makeMember('Pikachu', 88, ['Volt Tackle', 'Iron Tail', 'Quick Attack', 'Thunderbolt']),
      makeMember('Lapras', 80, ['Body Slam', 'Brine', 'Blizzard', 'Psychic']),
      makeMember('Snorlax', 82, ['Shadow Ball', 'Crunch', 'Blizzard', 'Giga Impact']),
      makeMember('Venusaur', 84, ['Frenzy Plant', 'Giga Drain', 'Sludge Bomb', 'Sleep Powder']),
      makeMember('Charizard', 84, ['Blast Burn', 'Flare Blitz', 'Air Slash', 'Dragon Pulse']),
      makeMember('Blastoise', 84, ['Hydro Cannon', 'Blizzard', 'Flash Cannon', 'Focus Blast']),
    ],
    gameData: {
      'gold-silver': {
        team: [
          makeMember('Pikachu', 81, ['Charm', 'Quick Attack', 'Thunderbolt', 'Thunder']),
          makeMember('Espeon', 73, ['Mud-Slap', 'Swift', 'Reflect', 'Psychic']),
          makeMember('Snorlax', 75, ['Amnesia', 'Snore', 'Rest', 'Body Slam']),
          makeMember('Venusaur', 77, ['Sunny Day', 'Giga Drain', 'Synthesis', 'SolarBeam']),
          makeMember('Charizard', 77, ['Flamethrower', 'Wing Attack', 'Slash', 'Fire Spin']),
          makeMember('Blastoise', 77, ['Rain Dance', 'Blizzard', 'Surf', 'Whirlpool']),
        ],
      },
    },
  }),
  ...[
    ['Roxanne', 'hoenn', 'Rustboro City Gym Leader', ['rock'], 'Nosepass', [makeMember('Geodude', 12, moves.rock), makeMember('Nosepass', 14, moves.rock)]],
    ['Brawly', 'hoenn', 'Dewford Town Gym Leader', ['fighting'], 'Makuhita', [makeMember('Machop', 14, moves.fighting), makeMember('Makuhita', 16, moves.fighting)]],
    ['Wattson', 'hoenn', 'Mauville City Gym Leader', ['electric'], 'Magneton', [makeMember('Magnemite', 19, moves.electric), makeMember('Voltorb', 19, moves.electric), makeMember('Magneton', 21, moves.electric)]],
    ['Flannery', 'hoenn', 'Lavaridge Town Gym Leader', ['fire'], 'Torkoal', [makeMember('Slugma', 26, moves.fire), makeMember('Numel', 26, moves.fire), makeMember('Torkoal', 28, moves.fire)]],
    ['Norman', 'hoenn', 'Petalburg City Gym Leader', ['normal'], 'Slaking', [makeMember('Slaking', 28, moves.normal), makeMember('Vigoroth', 28, moves.normal), makeMember('Slaking', 30, moves.normal)]],
    ['Winona', 'hoenn', 'Fortree City Gym Leader', ['flying'], 'Altaria', [makeMember('Swellow', 33, moves.flying), makeMember('Pelipper', 33, moves.water), makeMember('Skarmory', 33, moves.steel), makeMember('Altaria', 35, moves.dragon)]],
    ['Liza & Tate', 'hoenn', 'Mossdeep City Gym Leaders', ['psychic'], 'Solrock', [makeMember('Lunatone', 45, moves.psychic), makeMember('Solrock', 45, moves.psychic)]],
    ['Wallace', 'hoenn', 'Sootopolis City Gym Leader', ['water'], 'Milotic', [makeMember('Luvdisc', 44, moves.water), makeMember('Whiscash', 44, moves.water), makeMember('Sealeo', 44, moves.ice), makeMember('Seaking', 44, moves.water), makeMember('Milotic', 46, moves.water)]],
  ].map(([name, regionId, role, specialty, signature, team]) => makeTrainer({ id: `${name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${regionId}`, name, regionId, role, specialty, signature, summary: `${name} represents ${specialty.join(' / ')} types in the ${role}.`, team, gameData: getHoennGameData(name) })),
  makeTrainer({
    id: 'juan-hoenn',
    name: 'Juan',
    regionId: 'hoenn',
    role: 'Sootopolis City Gym Leader',
    specialty: ['water'],
    signature: 'Kingdra',
    summary: 'Juan replaces Wallace as Sootopolis Gym Leader in Pokemon Emerald.',
    team: hoennGameData.juan.emerald.team,
    gameIds: ['emerald'],
    gameData: hoennGameData.juan,
  }),
  ...[
    ['Sidney', 'hoenn', 'elite', 'Hoenn Elite Four', ['dark'], 'Absol', [makeMember('Mightyena', 50, moves.dark), makeMember('Shiftry', 50, moves.dark), makeMember('Cacturne', 50, moves.dark), makeMember('Sharpedo', 50, moves.water), makeMember('Absol', 52, moves.dark)]],
    ['Phoebe', 'hoenn', 'elite', 'Hoenn Elite Four', ['ghost'], 'Dusknoir', [makeMember('Dusclops', 51, moves.ghost), makeMember('Banette', 51, moves.ghost), makeMember('Sableye', 51, moves.dark), makeMember('Banette', 51, moves.ghost), makeMember('Dusknoir', 53, moves.ghost)]],
    ['Glacia', 'hoenn', 'elite', 'Hoenn Elite Four', ['ice'], 'Walrein', [makeMember('Glalie', 52, moves.ice), makeMember('Froslass', 52, moves.ice), makeMember('Glalie', 52, moves.ice), makeMember('Froslass', 52, moves.ice), makeMember('Walrein', 54, moves.ice)]],
    ['Drake', 'hoenn', 'elite', 'Hoenn Elite Four', ['dragon'], 'Salamence', [makeMember('Altaria', 53, moves.dragon), makeMember('Flygon', 53, moves.ground), makeMember('Kingdra', 53, moves.water), makeMember('Flygon', 53, moves.ground), makeMember('Salamence', 55, moves.dragon)]],
    ['Steven', 'hoenn', 'champion', 'Hoenn Champion', ['steel', 'rock'], 'Metagross', [makeMember('Skarmory', 57, moves.steel), makeMember('Claydol', 57, moves.psychic), makeMember('Aggron', 57, moves.steel), makeMember('Cradily', 57, moves.rock), makeMember('Armaldo', 57, moves.bug), makeMember('Metagross', 59, moves.steel)]],
  ].map(([name, regionId, division, role, specialty, signature, team]) => makeTrainer({ id: `${name.toLowerCase()}-${regionId}`, name, regionId, division, role, specialty, signature, summary: `${name} is a ${role} trainer specializing in ${specialty.join(' / ')} Pokemon.`, team, gameIds: name === 'Steven' ? ['ruby-sapphire', 'omega-ruby-alpha-sapphire'] : undefined, gameData: getHoennGameData(name) })),
  ...[
    ['Roark', 'sinnoh', 'Oreburgh City Gym Leader', ['rock'], 'Cranidos'],
    ['Gardenia', 'sinnoh', 'Eterna City Gym Leader', ['grass'], 'Roserade'],
    ['Wake', 'sinnoh', 'Pastoria City Gym Leader', ['water'], 'Floatzel'],
    ['Maylene', 'sinnoh', 'Veilstone City Gym Leader', ['fighting'], 'Lucario'],
    ['Fantina', 'sinnoh', 'Hearthome City Gym Leader', ['ghost'], 'Mismagius'],
    ['Byron', 'sinnoh', 'Canalave City Gym Leader', ['steel'], 'Bastiodon'],
    ['Candice', 'sinnoh', 'Snowpoint City Gym Leader', ['ice'], 'Abomasnow'],
    ['Volkner', 'sinnoh', 'Sunyshore City Gym Leader', ['electric'], 'Luxray'],
  ].map(([name, regionId, role, specialty, signature], index) => {
    const id = `${name.toLowerCase()}-${regionId}`;
    const team = sourceCheckedTrainerTeams[id] || [makeMember(signature, 14 + index * 5, moves[specialty[0]] || moves.normal), makeMember(index < 4 ? ['Geodude', 'Turtwig', 'Quagsire', 'Machoke'][index] : ['Drifblim', 'Steelix', 'Sneasel', 'Raichu'][index - 4], 12 + index * 5, moves[specialty[0]] || moves.normal)];
    return makeTrainer({ id, name, regionId, role, specialty, signature, summary: `${name} is a Sinnoh Gym Leader whose main challenge centers on ${specialty.join(' / ')} coverage.`, team });
  }),
  ...[
    ['Aaron', 'sinnoh', 'elite', 'Sinnoh Elite Four', ['bug'], 'Drapion'],
    ['Bertha', 'sinnoh', 'elite', 'Sinnoh Elite Four', ['ground'], 'Hippowdon'],
    ['Flint', 'sinnoh', 'elite', 'Sinnoh Elite Four', ['fire'], 'Infernape'],
    ['Lucian', 'sinnoh', 'elite', 'Sinnoh Elite Four', ['psychic'], 'Bronzong'],
    ['Cynthia', 'sinnoh', 'champion', 'Sinnoh Champion', ['mixed'], 'Garchomp'],
  ].map(([name, regionId, division, role, specialty, signature], index) => {
    const id = `${name.toLowerCase()}-${regionId}`;
    const team = sourceCheckedTrainerTeams[id] || [makeMember(signature, 53 + index, moves[specialty[0]] || moves.dragon), makeMember(['Yanmega', 'Rhyperior', 'Rapidash', 'Alakazam', 'Spiritomb'][index], 49 + index, moves[specialty[0]] || moves.ghost), makeMember(['Vespiquen', 'Gliscor', 'Steelix', 'Mr. Mime', 'Milotic'][index], 50 + index, moves[specialty[0]] || moves.water)];
    return makeTrainer({ id, name, regionId, division, role, specialty, signature, summary: `${name} is part of Sinnoh's Pokemon League challenge.`, team });
  }),
  ...[
    ['Cilan', 'unova', 'Striaton City Gym Leader', ['grass'], 'Pansage'],
    ['Chili', 'unova', 'Striaton City Gym Leader', ['fire'], 'Pansear'],
    ['Cress', 'unova', 'Striaton City Gym Leader', ['water'], 'Panpour'],
    ['Lenora', 'unova', 'Nacrene City Gym Leader', ['normal'], 'Watchog'],
    ['Burgh', 'unova', 'Castelia City Gym Leader', ['bug'], 'Leavanny'],
    ['Elesa', 'unova', 'Nimbasa City Gym Leader', ['electric'], 'Zebstrika'],
    ['Clay', 'unova', 'Driftveil City Gym Leader', ['ground'], 'Excadrill'],
    ['Skyla', 'unova', 'Mistralton City Gym Leader', ['flying'], 'Swanna'],
    ['Brycen', 'unova', 'Icirrus City Gym Leader', ['ice'], 'Beartic'],
    ['Drayden', 'unova', 'Opelucid City Gym Leader', ['dragon'], 'Haxorus'],
    ['Iris', 'unova', 'Opelucid City Gym Leader / Champion', ['dragon'], 'Haxorus'],
    ['Cheren', 'unova', 'Aspertia City Gym Leader', ['normal'], 'Stoutland'],
    ['Roxie', 'unova', 'Virbank City Gym Leader', ['poison'], 'Whirlipede'],
  ].map(([name, regionId, role, specialty, signature], index) => {
    const id = `${name.toLowerCase()}-${regionId}`;
    const team = sourceCheckedTrainerTeams[id] || [makeMember(signature, 14 + index * 3, moves[specialty[0]] || moves.dragon), makeMember(['Lillipup', 'Tepig', 'Oshawott', 'Herdier', 'Dwebble', 'Emolga', 'Krokorok', 'Swoobat', 'Cryogonal', 'Druddigon', 'Druddigon', 'Patrat', 'Koffing'][index], 12 + index * 3, moves[specialty[0]] || moves.normal)];
    return makeTrainer({ id, name, regionId, role, specialty, signature, summary: `${name} appears in Unova's Gym challenge with a ${specialty.join(' / ')}-focused team.`, team });
  }),
  ...[
    ['Shauntal', 'unova', 'elite', 'Unova Elite Four', ['ghost'], 'Chandelure'],
    ['Grimsley', 'unova', 'elite', 'Unova Elite Four', ['dark'], 'Bisharp'],
    ['Caitlin', 'unova', 'elite', 'Unova Elite Four', ['psychic'], 'Gothitelle'],
    ['Marshal', 'unova', 'elite', 'Unova Elite Four', ['fighting'], 'Conkeldurr'],
    ['Alder', 'unova', 'champion', 'Unova Champion', ['mixed'], 'Volcarona'],
  ].map(([name, regionId, division, role, specialty, signature], index) => {
    const id = `${name.toLowerCase()}-${regionId}`;
    const team = sourceCheckedTrainerTeams[id] || [makeMember(signature, 50 + index, moves[specialty[0]] || moves.bug), makeMember(['Cofagrigus', 'Scrafty', 'Reuniclus', 'Throh', 'Bouffalant'][index], 48 + index, moves[specialty[0]] || moves.normal), makeMember(['Golurk', 'Krookodile', 'Sigilyph', 'Sawk', 'Druddigon'][index], 48 + index, moves[specialty[0]] || moves.dragon)];
    return makeTrainer({ id, name, regionId, division, role, specialty, signature, summary: `${name} is part of Unova's Pokemon League challenge.`, team, gameData: getUnovaGameData(name) });
  }),
  ...[
    ['Viola', 'kalos', 'Santalune City Gym Leader', ['bug'], 'Vivillon'],
    ['Grant', 'kalos', 'Cyllage City Gym Leader', ['rock'], 'Tyrunt'],
    ['Korrina', 'kalos', 'Shalour City Gym Leader', ['fighting'], 'Lucario'],
    ['Ramos', 'kalos', 'Coumarine City Gym Leader', ['grass'], 'Gogoat'],
    ['Clemont', 'kalos', 'Lumiose City Gym Leader', ['electric'], 'Heliolisk'],
    ['Valerie', 'kalos', 'Laverre City Gym Leader', ['fairy'], 'Sylveon'],
    ['Olympia', 'kalos', 'Anistar City Gym Leader', ['psychic'], 'Meowstic'],
    ['Wulfric', 'kalos', 'Snowbelle City Gym Leader', ['ice'], 'Avalugg'],
    ['Malva', 'kalos', 'elite', 'Kalos Elite Four', ['fire'], 'Talonflame'],
    ['Siebold', 'kalos', 'elite', 'Kalos Elite Four', ['water'], 'Clawitzer'],
    ['Wikstrom', 'kalos', 'elite', 'Kalos Elite Four', ['steel'], 'Aegislash-shield'],
    ['Drasna', 'kalos', 'elite', 'Kalos Elite Four', ['dragon'], 'Noivern'],
    ['Diantha', 'kalos', 'champion', 'Kalos Champion', ['mixed'], 'Gardevoir'],
  ].map(([name, regionId, divisionOrRole, roleOrSpecialty, specialtyOrSignature, signatureMaybe], index) => {
    const division = ['elite', 'champion'].includes(divisionOrRole) ? divisionOrRole : 'gym';
    const role = division === 'gym' ? divisionOrRole : roleOrSpecialty;
    const specialty = division === 'gym' ? roleOrSpecialty : specialtyOrSignature;
    const signature = division === 'gym' ? specialtyOrSignature : signatureMaybe;
    const id = `${name.toLowerCase()}-${regionId}`;
    const team = sourceCheckedTrainerTeams[id] || [makeMember(signature, 12 + index * 4, moves[specialty[0]] || moves.psychic), makeMember(['Surskit', 'Amaura', 'Machoke', 'Jumpluff', 'Magneton', 'Mr. Mime', 'Slowking', 'Cryogonal', 'Pyroar', 'Starmie', 'Probopass', 'Dragalge', 'Hawlucha'][index], 10 + index * 4, moves[specialty[0]] || moves.flying)];
    return makeTrainer({ id, name, regionId, division, role, specialty, signature, summary: `${name} is a Kalos ${division === 'gym' ? 'Gym Leader' : 'League trainer'} using ${specialty.join(' / ')} pressure.`, team, gameIds: ['x-y'] });
  }),
  ...legendsZaTrainers,
  ...[
    ['Hala', 'alola', 'kahuna', 'Melemele Island Kahuna', ['fighting'], 'Crabrawler', [makeMember('Mankey', 14, moves.fighting), makeMember('Makuhita', 14, moves.fighting), makeMember('Crabrawler', 15, moves.fighting)]],
    ['Olivia', 'alola', 'kahuna', 'Akala Island Kahuna', ['rock'], 'Lycanroc', [makeMember('Nosepass', 26, moves.rock), makeMember('Boldore', 26, moves.rock), makeMember('Lycanroc-midday', 27, moves.rock, 'Lycanroc')]],
    ['Nanu', 'alola', 'kahuna', 'Ula\'ula Island Kahuna', ['dark'], 'Persian', [makeMember('Sableye', 38, moves.dark), makeMember('Krokorok', 38, moves.ground), makeMember('Persian-alola', 39, moves.dark, 'Persian')]],
    ['Hapu', 'alola', 'kahuna', 'Poni Island Kahuna', ['ground'], 'Mudsdale', [makeMember('Dugtrio-alola', 47, moves.ground, 'Dugtrio'), makeMember('Flygon', 47, moves.dragon), makeMember('Gastrodon', 47, moves.water), makeMember('Mudsdale', 48, moves.ground)]],
    ['Acerola', 'alola', 'elite', 'Alola Elite Four', ['ghost'], 'Palossand', [makeMember('Sableye', 54, moves.dark), makeMember('Drifblim', 54, moves.ghost), makeMember('Dhelmise', 54, moves.ghost), makeMember('Froslass', 54, moves.ice), makeMember('Palossand', 55, moves.ghost)]],
    ['Kahili', 'alola', 'elite', 'Alola Elite Four', ['flying'], 'Toucannon', [makeMember('Skarmory', 54, moves.steel), makeMember('Crobat', 54, moves.poison), makeMember('Oricorio-baile', 54, moves.fire, 'Oricorio'), makeMember('Mandibuzz', 54, moves.dark), makeMember('Toucannon', 55, moves.flying)]],
    ['Kukui', 'alola', 'champion', 'Alola Pokemon League Final', ['mixed'], 'Lycanroc', [makeMember('Lycanroc-midday', 57, moves.rock, 'Lycanroc'), makeMember('Ninetales-alola', 56, moves.ice, 'Ninetales'), makeMember('Braviary', 56, moves.flying), makeMember('Magnezone', 56, moves.electric), makeMember('Snorlax', 56, moves.normal), makeMember('Incineroar', 58, moves.fire)]],
  ].map(([name, regionId, division, role, specialty, signature, team]) => makeTrainer({ id: `${name.toLowerCase()}-${regionId}`, name, regionId, division, role, specialty, signature, summary: `${name} is part of Alola's island challenge or League path.`, team })),
  ...[
    ['Milo', 'galar', 'Turffield Stadium Gym Leader', ['grass'], 'Eldegoss'],
    ['Nessa', 'galar', 'Hulbury Stadium Gym Leader', ['water'], 'Drednaw'],
    ['Kabu', 'galar', 'Motostoke Stadium Gym Leader', ['fire'], 'Centiskorch'],
    ['Bea', 'galar', 'Stow-on-Side Stadium Gym Leader', ['fighting'], 'Machamp'],
    ['Allister', 'galar', 'Stow-on-Side Stadium Gym Leader', ['ghost'], 'Gengar'],
    ['Opal', 'galar', 'Ballonlea Stadium Gym Leader', ['fairy'], 'Alcremie'],
    ['Gordie', 'galar', 'Circhester Stadium Gym Leader', ['rock'], 'Coalossal'],
    ['Melony', 'galar', 'Circhester Stadium Gym Leader', ['ice'], 'Lapras'],
    ['Piers', 'galar', 'Spikemuth Gym Leader', ['dark'], 'Obstagoon'],
    ['Raihan', 'galar', 'Hammerlocke Stadium Gym Leader', ['dragon'], 'Duraludon'],
    ['Leon', 'galar', 'champion', 'Galar Champion', ['mixed'], 'Charizard'],
  ].map(([name, regionId, divisionOrRole, roleOrSpecialty, specialtyOrSignature, signatureMaybe], index) => {
    const division = divisionOrRole === 'champion' ? 'champion' : 'gym';
    const role = division === 'gym' ? divisionOrRole : roleOrSpecialty;
    const specialty = division === 'gym' ? roleOrSpecialty : specialtyOrSignature;
    const signature = division === 'gym' ? specialtyOrSignature : signatureMaybe;
    const id = `${name.toLowerCase()}-${regionId}`;
    const team = sourceCheckedTrainerTeams[id] || [makeMember(signature, 20 + index * 4, moves[specialty[0]] || moves.fire), makeMember(['Gossifleur', 'Arrokuda', 'Ninetales', 'Sirfetchd', 'Mimikyu', 'Weezing-galar', 'Shuckle', 'Frosmoth', 'Scrafty', 'Flygon', 'Aegislash-shield'][index], 18 + index * 4, moves[specialty[0]] || moves.dragon)];
    return makeTrainer({ id, name, regionId, division, role, specialty, signature, summary: `${name} represents Galar's stadium-format Gym Challenge.`, team });
  }),
  ...[
    ['Katy', 'paldea', 'Cortondo Gym Leader', ['bug'], 'Ursaring'],
    ['Brassius', 'paldea', 'Artazon Gym Leader', ['grass'], 'Sudowoodo'],
    ['Iono', 'paldea', 'Levincia Gym Leader', ['electric'], 'Mismagius'],
    ['Kofu', 'paldea', 'Cascarrafa Gym Leader', ['water'], 'Crabominable'],
    ['Larry', 'paldea', 'Medali Gym Leader', ['normal'], 'Staraptor'],
    ['Ryme', 'paldea', 'Montenevera Gym Leader', ['ghost'], 'Toxtricity'],
    ['Tulip', 'paldea', 'Alfornada Gym Leader', ['psychic'], 'Florges'],
    ['Grusha', 'paldea', 'Glaseado Gym Leader', ['ice'], 'Altaria'],
    ['Rika', 'paldea', 'elite', 'Paldea Elite Four', ['ground'], 'Clodsire'],
    ['Poppy', 'paldea', 'elite', 'Paldea Elite Four', ['steel'], 'Tinkaton'],
    ['Larry', 'paldea-elite', 'elite', 'Paldea Elite Four', ['flying'], 'Flamigo'],
    ['Hassel', 'paldea', 'elite', 'Paldea Elite Four', ['dragon'], 'Baxcalibur'],
    ['Geeta', 'paldea', 'champion', 'Paldea Top Champion', ['mixed'], 'Glimmora'],
  ].map(([name, regionIdRaw, divisionOrRole, roleOrSpecialty, specialtyOrSignature, signatureMaybe], index) => {
    const regionId = regionIdRaw === 'paldea-elite' ? 'paldea' : regionIdRaw;
    const division = ['elite', 'champion'].includes(divisionOrRole) ? divisionOrRole : 'gym';
    const role = division === 'gym' ? divisionOrRole : roleOrSpecialty;
    const specialty = division === 'gym' ? roleOrSpecialty : specialtyOrSignature;
    const signature = division === 'gym' ? specialtyOrSignature : signatureMaybe;
    const id = `${name.toLowerCase()}-${regionIdRaw}`;
    const team = sourceCheckedTrainerTeams[id] || [makeMember(signature, 15 + index * 4, moves[specialty[0]] || moves.rock), makeMember(['Nymble', 'Petilil', 'Wattrel', 'Wugtrio', 'Komala', 'Banette', 'Farigiraf', 'Frosmoth', 'Whiscash', 'Corviknight', 'Tropius', 'Noivern', 'Espathra'][index], 14 + index * 4, moves[specialty[0]] || moves.psychic)];
    return makeTrainer({ id, name, regionId, division, role, specialty, signature, summary: `${name} is a Paldea ${division === 'gym' ? 'Gym Leader' : 'League trainer'} with a ${specialty.join(' / ')} focus.`, team });
  }),
  makeTrainer({
    id: 'n-unova',
    name: 'N',
    regionId: 'unova',
    division: 'rival',
    role: 'Team Plasma King',
    specialty: ['mixed'],
    signature: 'Zekrom',
    summary: 'N is Team Plasma\'s king and returns in Black 2 / White 2 for seasonal postgame battles at N\'s Castle.',
    team: makeTeam([['Reshiram', 52, 'fire'], ['Zoroark', 50, 'dark'], ['Vanilluxe', 50, 'ice'], ['Klinklang', 50, 'steel'], ['Carracosta', 50, 'water'], ['Archeops', 50, 'rock']]),
    gameData: {
      'black-white': {
        role: 'N\'s Castle Final Boss',
        signature: 'Reshiram',
        team: makeTeam([['Reshiram', 52, 'fire'], ['Zoroark', 50, 'dark'], ['Vanilluxe', 50, 'ice'], ['Klinklang', 50, 'steel'], ['Carracosta', 50, 'water'], ['Archeops', 50, 'rock']]),
      },
      'black-2-white-2': {
        role: 'N\'s Castle Postgame Rematch',
        team: makeTeam([['Zekrom', 70, 'electric'], ['Carracosta', 75, 'water'], ['Archeops', 75, 'rock'], ['Vanilluxe', 75, 'ice'], ['Zoroark', 75, 'dark'], ['Klinklang', 75, 'steel']]),
        battleStages: {
          summer: { label: 'Summer Rematch', team: makeTeam([['Ninetales', 77, 'fire'], ['Arcanine', 75, 'fire'], ['Rapidash', 75, 'fire'], ['Darmanitan-standard', 75, 'fire', 'Darmanitan'], ['Chandelure', 75, 'ghost'], ['Volcarona', 77, 'bug']]) },
          winter: { label: 'Winter Rematch', team: makeTeam([['Abomasnow', 77, 'ice'], ['Vanilluxe', 75, 'ice'], ['Froslass', 75, 'ice'], ['Mamoswine', 75, 'ice'], ['Glaceon', 75, 'ice'], ['Weavile', 77, 'dark']]) },
        },
      },
    },
  }),
  makeTrainer({
    id: 'cynthia-unova',
    name: 'Cynthia',
    regionId: 'unova',
    division: 'postgame',
    role: 'Undella Town Postgame Boss',
    specialty: ['mixed'],
    signature: 'Garchomp',
    summary: 'Cynthia visits Undella Town in Unova and can be challenged as a postgame boss.',
    team: makeTeam([['Spiritomb', 75, 'ghost'], ['Eelektross', 75, 'electric'], ['Braviary', 75, 'flying'], ['Lucario', 75, 'fighting'], ['Milotic', 75, 'water'], ['Garchomp', 77, 'dragon']]),
    gameData: {
      'black-white': { team: makeTeam([['Spiritomb', 75, 'ghost'], ['Eelektross', 75, 'electric'], ['Braviary', 75, 'flying'], ['Lucario', 75, 'fighting'], ['Milotic', 75, 'water'], ['Garchomp', 77, 'dragon']]) },
      'black-2-white-2': { role: 'Undella Town / PWT Champion', team: makeTeam([['Spiritomb', 76, 'ghost'], ['Glaceon', 76, 'ice'], ['Togekiss', 76, 'fairy'], ['Lucario', 76, 'fighting'], ['Milotic', 76, 'water'], ['Garchomp', 78, 'dragon']]) },
    },
  }),
  makeTrainer({
    id: 'benga-unova',
    name: 'Benga',
    regionId: 'unova',
    division: 'facility',
    role: 'Black Tower / White Treehollow Boss Trainer',
    specialty: ['mixed'],
    signature: 'Latios',
    summary: 'Benga is the final Boss Trainer of Area 10 in Black Tower or White Treehollow.',
    team: makeTeam([['Latios', 80, 'dragon'], ['Garchomp', 80, 'dragon'], ['Volcarona', 80, 'bug']]),
    gameIds: ['black-2-white-2'],
    gameData: {
      'black-2-white-2': {
        battleStages: {
          'white-treehollow': { label: 'White Treehollow', team: makeTeam([['Latias', 80, 'dragon'], ['Dragonite', 80, 'dragon'], ['Volcarona', 80, 'bug']]) },
        },
      },
    },
  }),
  makeTrainer({
    id: 'colress-unova',
    name: 'Colress',
    regionId: 'unova',
    division: 'postgame',
    role: 'Plasma Frigate Postgame Rematch',
    specialty: ['steel', 'electric'],
    signature: 'Klinklang',
    summary: 'Colress can be rematched aboard the Plasma Frigate after the Black 2 / White 2 story.',
    team: makeTeam([['Magneton', 72, 'electric'], ['Magnezone', 72, 'electric'], ['Beheeyem', 72, 'psychic'], ['Metagross', 72, 'steel'], ['Rotom', 72, 'electric'], ['Klinklang', 74, 'steel']]),
    gameIds: ['black-2-white-2'],
  }),
  makeTrainer({
    id: 'wally-hoenn',
    name: 'Wally',
    regionId: 'hoenn',
    division: 'rival',
    role: 'Battle Resort Rematch',
    specialty: ['mixed'],
    signature: 'Gallade',
    summary: 'Wally returns at the Battle Resort in Omega Ruby / Alpha Sapphire for stronger rematches.',
    team: makeTeam([['Altaria', 79, 'dragon'], ['Delcatty', 79, 'normal'], ['Roselia', 79, 'grass'], ['Magnezone', 79, 'electric'], ['Azumarill', 79, 'water'], ['Gallade', 81, 'psychic']]),
    gameIds: ['omega-ruby-alpha-sapphire'],
  }),
  makeTrainer({
    id: 'zinnia-hoenn',
    name: 'Zinnia',
    regionId: 'hoenn',
    division: 'postgame',
    role: 'Delta Episode Final Boss',
    specialty: ['dragon'],
    signature: 'Rayquaza',
    summary: 'Zinnia is the climactic Delta Episode battle in Omega Ruby / Alpha Sapphire.',
    team: makeTeam([['Goodra', 60, 'dragon'], ['Tyrantrum', 60, 'rock'], ['Altaria', 60, 'dragon'], ['Noivern', 60, 'dragon'], ['Salamence', 62, 'dragon']]),
    gameIds: ['omega-ruby-alpha-sapphire'],
  }),
  makeTrainer({
    id: 'red-alola',
    name: 'Red',
    regionId: 'alola',
    division: 'facility',
    role: 'Battle Tree Boss',
    specialty: ['mixed'],
    signature: 'Charizard',
    summary: 'Red appears as a Battle Tree boss in Alola alongside Blue.',
    team: makeTeam([['Venusaur', 50, 'grass'], ['Charizard', 50, 'fire'], ['Blastoise', 50, 'water'], ['Lapras', 50, 'water'], ['Snorlax', 50, 'normal'], ['Pikachu', 50, 'electric']]),
    gameIds: ['sun-moon'],
  }),
  makeTrainer({
    id: 'blue-alola',
    name: 'Blue',
    regionId: 'alola',
    division: 'facility',
    role: 'Battle Tree Boss',
    specialty: ['mixed'],
    signature: 'Alakazam',
    summary: 'Blue appears as a Battle Tree boss in Alola alongside Red.',
    team: makeTeam([['Alakazam', 50, 'psychic'], ['Machamp', 50, 'fighting'], ['Exeggutor', 50, 'grass'], ['Arcanine', 50, 'fire'], ['Gyarados', 50, 'water'], ['Aerodactyl', 50, 'rock']]),
    gameIds: ['sun-moon'],
  }),
  makeTrainer({
    id: 'cynthia-alola',
    name: 'Cynthia',
    regionId: 'alola',
    division: 'facility',
    role: 'Battle Tree Trainer',
    specialty: ['mixed'],
    signature: 'Garchomp',
    summary: 'Cynthia returns as a Battle Tree trainer in Alola.',
    team: makeTeam([['Spiritomb', 50, 'ghost'], ['Milotic', 50, 'water'], ['Togekiss', 50, 'fairy'], ['Lucario', 50, 'fighting'], ['Roserade', 50, 'grass'], ['Garchomp', 50, 'dragon']]),
    gameIds: ['sun-moon'],
  }),
  makeTrainer({
    id: 'mustard-galar',
    name: 'Mustard',
    regionId: 'galar',
    division: 'postgame',
    role: 'Master Dojo Final Boss',
    specialty: ['fighting'],
    signature: 'Urshifu',
    summary: 'Mustard is the Isle of Armor Master Dojo final battle after the Galar main story.',
    team: makeTeam([['Mienshao', 73, 'fighting'], ['Luxray', 73, 'electric'], ['Corviknight', 74, 'flying'], ['Lycanroc-dusk', 75, 'rock', 'Lycanroc'], ['Kommo-o', 75, 'dragon'], ['Urshifu-single-strike', 75, 'fighting', 'Urshifu']]),
    gameIds: ['sword-shield'],
  }),
  makeTrainer({
    id: 'kieran-paldea',
    name: 'Kieran',
    regionId: 'paldea',
    division: 'rival',
    role: 'Blueberry Academy Champion',
    specialty: ['mixed'],
    signature: 'Hydrapple',
    summary: 'Kieran becomes Blueberry Academy Champion in The Indigo Disk and challenges the player in a Double Battle.',
    team: makeTeam([['Dragonite', 80, 'dragon'], ['Politoed', 80, 'water'], ['Porygon-Z', 81, 'normal'], ['Grimmsnarl', 81, 'dark'], ['Incineroar', 81, 'fire'], ['Hydrapple', 82, 'grass']]),
    gameIds: ['scarlet-violet'],
  }),
];
